language: csharp
mono: none
dotnet: 2.0.3
dist: trusty
solution: src/AutoMoq.sln
script:
  - dotnet add src/AutoMoq.Tests/AutoMoq.Tests.csproj package dotnet-xunit
  - dotnet build src/AutoMoq.sln --configuration Release  
  - dotnet test src/AutoMoq.Tests/AutoMoq.Tests.csproj
  - dotnet xunit src/AutoMoq.Tests/AutoMoq.Tests.csproj
